graph TD;
    75-->40;
    75-->89;
    40-->12;
    40-->\;
    12-->9;
    12-->35;
    9-->1;
    9-->\\;
    1-->\\\;
    1-->2
    2-->\\\\;
    2-->7;
    7-->3;
    7-->\\\\\;
    89-->66;
    89-->128;
    128-->99;
    128-->/;
    35-->27;
    35-->36
    3-->//;
    3-->4;
    66-->55;
    66-->///;